name: Build and Test
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron:  '0 7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout azure-javaee-iaas
        uses: actions/checkout@v2
        with:
          repository: Azure/azure-javaee-iaas
          path: azure-javaee-iaas        
          ref: 7ace9c4c8a9a9260f1ee3852276285ae2a0df8c2
      - name: Checkout arm-ttk
        uses: actions/checkout@v2
        with:
          repository: Azure/arm-ttk
          path: arm-ttk    
          ref: e2fbdcb93a4b2004c9ea953956b85248e0ef8c1c
      - name: Checkout arm-oraclelinux-wls-dynamic-cluster
        uses: actions/checkout@v2
        with:
          path: arm-oraclelinux-wls-dynamic-cluster  
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build azure-javaee-iaas
        run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
      - name: Built and test arm-oraclelinux-wls-dynamic-cluster        
        run: mvn -Ptemplate-validation-tests clean install --file arm-oraclelinux-wls-dynamic-cluster/pom.xml

      - name: Get version information from arm-oraclelinux-wls-dynamic-cluster/pom.xml
        id: version
        run: echo "##[set-env name=version;]$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-dynamic-cluster/arm-oraclelinux-wls-dynamic-cluster/pom.xml)"
      - name: Print version
        run: echo $version 
      - name: Generate artifact name         
        run: echo "##[set-env name=artifactName;]arm-oraclelinux-wls-dynamic-cluster-$version-arm-assembly"  
      - name: Print artifact name
        run: echo $artifactName
      - name: Output artifact name
        id: artifact_file
        run: echo "##[set-output name=artifactName;]arm-oraclelinux-wls-dynamic-cluster-$version-arm-assembly"
      - name: Generate zip package path
        id: artifact_path
        run: echo "##[set-output name=artifactPath;]arm-oraclelinux-wls-dynamic-cluster/arm-oraclelinux-wls-dynamic-cluster/target/$artifactName"
      - name: Output artifact path
        run: echo $artifactPath
        env: 
          artifactPath: ${{steps.package.outputs.artifactPath}}
      - name: Unzip the package as upload action will zip again 
        run: unzip arm-oraclelinux-wls-dynamic-cluster/arm-oraclelinux-wls-dynamic-cluster/target/$artifactName.zip -d arm-oraclelinux-wls-dynamic-cluster/arm-oraclelinux-wls-dynamic-cluster/target/$artifactName

      - name: Archive arm-oraclelinux-wls-dynamic-cluster template
        uses: actions/upload-artifact@v1 
        if: success()
        with:
          name: ${{steps.artifact_file.outputs.artifactName}}
          path: ${{steps.artifact_path.outputs.artifactPath}}

      - name: Get version information from addnode/pom.xml
        id: addnode_version
        run: echo "##[set-env name=addnode_version;]$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-dynamic-cluster/addnode/pom.xml)"
      - name: Print addnode template version
        run: echo $addnode_version 
      - name: Generate artifact name         
        run: echo "##[set-env name=addnode_artifactName;]arm-oraclelinux-wls-dynamic-cluster-addnode-$addnode_version-arm-assembly"  
      - name: Print addnode template artifact name
        run: echo $addnode_artifactName
      - name: Output addnode template artifact name
        id: addnode_artifact_file
        run: echo "##[set-output name=addnode_artifactName;]arm-oraclelinux-wls-dynamic-cluster-addnode-$addnode_version-arm-assembly"
      - name: Generate zip package path
        id: addnode_artifact_path
        run: echo "##[set-output name=addnode_artifactPath;]arm-oraclelinux-wls-dynamic-cluster/addnode/target/$addnode_artifactName"
      - name: Output addnode template artifact path
        run: echo $addnode_artifactPath
        env: 
          $addnode_artifactPath: ${{steps.addnode_artifact_path.outputs.addnode_artifactPath}}
      - name: Unzip the package as upload action will zip again 
        run: unzip arm-oraclelinux-wls-dynamic-cluster/addnode/target/$addnode_artifactName.zip -d arm-oraclelinux-wls-dynamic-cluster/addnode/target/$addnode_artifactName

      - name: Archive arm-oraclelinux-wls-dynamic-cluster addnode template
        uses: actions/upload-artifact@v1 
        if: success()
        with:
          name: ${{steps.addnode_artifact_file.outputs.addnode_artifactName}}
          path: ${{steps.addnode_artifact_path.outputs.addnode_artifactPath}}
